# frontend/Dockerfile
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json tsconfig.json vite.config.* ./
RUN npm install

COPY . .
RUN vite build

# Serve with nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
