
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: my_database
    ports:
      - "5433:5433"
    volumes:
      - ./db:/docker-entrypoint-initdb.d 
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: beccalin/advanced-fs-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend        # Mount backend source code
      - backend_node_modules:/backend/node_modules     # separate volume for node_modules
    environment:
      DATABASE_URL: postgres://postgres:my-secret-pw@db:5432/my_database
      JWT_SECRET: 123SuperCauliflowerABC!
      REFRESH_TOKEN_SECRET: super123SecretBroccoliABC!
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: beccalin/advanced-fs-frontend:latest
    ports:
      - "5173:5173"          # Vite dev server port
    volumes:
      - ./frontend:/app       # Mount frontend source code
      - /app/node_modules     # Container manages node_modules
    command: ["npm", "run", "dev"]
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    depends_on:
      - backend

volumes:
  db-data:
  backend_node_modules:
